<template>
  <q-layout view="hHh lpR fFf">

    <q-header class="bg-primary text-white">
    <header></header>
    </q-header>

    <q-page-container>
      <router-view></router-view>
    </q-page-container>

    <q-footer class="bg-grey-8 text-white">
      <q-toolbar>

      </q-toolbar>
    </q-footer>

  </q-layout>
</template>

<script>
import Header from './components/Header'
//import {Meteor} from 'meteor/meteor';
import {
  QAjaxBar,
  QAvatar,
  QBadge,
  QBanner,
  QBar,
  QBreadcrumbs,
  QBreadcrumbsEl,
  QBtnDropdown,
  QBtnGroup,
  QBtnToggle,
  QBtn,
  QCard,
  QCardActions,
  QCardSection,
  QCarousel,
  QCarouselControl,
  QCarouselSlide,
  QChatMessage,
  QCheckbox,
  QChip,
  QCircularProgress,
  QColor,
  QDate,
  QDialog,
  QDrawer,
  QEditor,
  QExpansionItem,
  QFab,
  QFabAction,
  QField,
  QFile,
  QFooter,
  QForm,
  QHeader,
  QIcon,
  QImg,
  QInfiniteScroll,
  QInnerLoading,
  QInput,
  QIntersection,
  QItem,
  QItemLabel,
  QItemSection,
  QList,
  QKnob,
  QLayout,
  QLinearProgress,
  QMarkupTable,
  QMenu,
  QNoSsr,
  QOptionGroup,
  QPageScroller,
  QPageSticky,
  QPage,
  QPageContainer,
  QPagination,
  QParallax,
  QPopupEdit,
  QPopupProxy,
  QPullToRefresh,
  QRadio,
  QRange,
  QRating,
  QResizeObserver,
  QResponsive,
  QScrollArea,
  QScrollObserver,
  QSelect,
  QSeparator,
  QSkeleton,
  QSlideItem,
  QSlideTransition,
  QSlider,
  QSpace,
  QSpinner,
  QSpinnerAudio,
  QSpinnerBall,
  QSpinnerBars,
  QSpinnerComment,
  QSpinnerCube,
  QSpinnerDots,
  QSpinnerFacebook,
  QSpinnerGears,
  QSpinnerGrid,
  QSpinnerHearts,
  QSpinnerHourglass,
  QSpinnerInfinity,
  QSpinnerIos,
  QSpinnerOval,
  QSpinnerPie,
  QSpinnerPuff,
  QSpinnerRadio,
  QSpinnerRings,
  QSpinnerTail,
  QSplitter,
  QStep,
  QStepper,
  QStepperNavigation,
  QTabPanel,
  QTabPanels,
  QTable,
  QTd,
  QTh,
  QTr,
  QRouteTab,
  QTab,
  QTabs,
  QTime,
  QTimeline,
  QTimelineEntry,
  QToggle,
  QToolbar,
  QToolbarTitle,
  QTooltip,
  QUploader,
  QUploaderAddTrigger,
  QUploaderBase,
  QVideo,
  QVirtualScroll

} from 'quasar';
//See main.js for the global import of 'Quasar' and vue.use() method.
//Don't move the 'Quasar' import from main.js - importing 'Quasar' later causes an error
import "@quasar/extras/material-icons/material-icons.css";
import "quasar/dist/quasar.min.css";
import "quasar/dist/quasar.umd.min";

// To make the material-icons appear, we also have to add links in the /public folder
// to the web-font folder with the .css and .woff files
// in node_modules/@quasar/extras/material-icons.
//I find that this import for the material-icons needs to come after all the other quasar imports

export default {
  name: 'MainLayout',

  components: {
    Header,
    QAjaxBar,
    QAvatar,
    QBadge,
    QBanner,
    QBar,
    QBreadcrumbs,
    QBreadcrumbsEl,
    QBtnDropdown,
    QBtnGroup,
    QBtnToggle,
    QBtn,
    QCard,
    QCardActions,
    QCardSection,
    QCarousel,
    QCarouselControl,
    QCarouselSlide,
    QChatMessage,
    QCheckbox,
    QChip,
    QCircularProgress,
    QColor,
    QDate,
    QDialog,
    QDrawer,
    QEditor,
    QExpansionItem,
    QFab,
    QFabAction,
    QField,
    QFile,
    QFooter,
    QForm,
    QHeader,
    QIcon,
    QImg,
    QInfiniteScroll,
    QInnerLoading,
    QInput,
    QIntersection,
    QItem,
    QItemLabel,
    QItemSection,
    QList,
    QKnob,
    QLayout,
    QLinearProgress,
    QMarkupTable,
    QMenu,
    QNoSsr,
    QOptionGroup,
    QPageScroller,
    QPageSticky,
    QPage,
    QPageContainer,
    QPagination,
    QParallax,
    QPopupEdit,
    QPopupProxy,
    QPullToRefresh,
    QRadio,
    QRange,
    QRating,
    QResizeObserver,
    QResponsive,
    QScrollArea,
    QScrollObserver,
    QSelect,
    QSeparator,
    QSkeleton,
    QSlideItem,
    QSlideTransition,
    QSlider,
    QSpace,
    QSpinner,
    QSpinnerAudio,
    QSpinnerBall,
    QSpinnerBars,
    QSpinnerComment,
    QSpinnerCube,
    QSpinnerDots,
    QSpinnerFacebook,
    QSpinnerGears,
    QSpinnerGrid,
    QSpinnerHearts,
    QSpinnerHourglass,
    QSpinnerInfinity,
    QSpinnerIos,
    QSpinnerOval,
    QSpinnerPie,
    QSpinnerPuff,
    QSpinnerRadio,
    QSpinnerRings,
    QSpinnerTail,
    QSplitter,
    QStep,
    QStepper,
    QStepperNavigation,
    QTabPanel,
    QTabPanels,
    QTable,
    QTd,
    QTh,
    QTr,
    QRouteTab,
    QTab,
    QTabs,
    QTime,
    QTimeline,
    QTimelineEntry,
    QToggle,
    QToolbar,
    QToolbarTitle,
    QTooltip,
    QUploader,
    QUploaderAddTrigger,
    QUploaderBase,
    QVideo,
    QVirtualScroll
  },
  data: function () {
    return {}
  }

}
</script>
